language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby
jdk:
  - oraclejdk7
  - openjdk7
before_script:
  - bundle exec rake neo4j:server:install neo4j:server:start
after_script:
  - bundle exec rake neo4j:server:stop
