ruby:
  adapter: sqlite3
  database: ":memory:"
  encoding: utf8
  charset: utf8
  timeout: 5000

jruby:
  adapter: jdbcsqlite3
  database: ":memory:"
  encoding: utf8
  charset: utf8
  timeout: 5000
